import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { file, glob } from 'astro/loaders';

/**
 * Content collections — shaped from Figma "03 — Content Systems" (11:74).
 *
 * Layout follows the structure sketched in FIGMA.md: builds are one file per
 * entry (they grow indefinitely and each carries a photo set), while games,
 * books and projects are single JSON arrays.
 *
 * These schemas are also the contract the .NET API will need to satisfy
 * later, so they are deliberately explicit rather than loose.
 */

/** Figma "Status Label" (33:41) variants. */
const status = z.enum(['live', 'archive', 'draft']);

/**
 * A / BUILD ARCHIVE — "RG / 1:144 / MOBILE SUIT", model name,
 * "Series · Manufacturer · Build date", build notes, photo set.
 *
 * These files are generated by `npm run blog:sync` from the Blogspot feed and
 * committed. Do not hand-edit them — the next sync overwrites the file. To
 * correct or supply a field, add it to src/content/builds-overrides.json.
 *
 * `grade`, `scale` and `series` are optional because the feed cannot always
 * supply them: third-party makers (Daban, Shenma, Hemoxian) do not use Bandai
 * grade names, and non-scale kits have no meaningful scale. Every consumer
 * has to tolerate their absence rather than render an empty separator.
 */
const builds = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/builds' }),
  schema: z.object({
    title: z.string(),
    /** Kit grade — RG, MG, HG, PG. Rendered in the kicker when known. */
    grade: z.string().optional(),
    scale: z.string().optional(),
    kind: z.string(),
    series: z.string().optional(),
    manufacturer: z.string(),
    buildDate: z.string(),
    /** Empty for the occasional photo-only post that has no prose at all. */
    summary: z.string().default(''),
    /** Panel lining / custom paint / decals / modifications. */
    notes: z.array(z.string()).default([]),
    /** Bullets the post filed under "Pros:" / "Cons:", kept apart so the
     *  detail page does not present a complaint as a recommendation. */
    pros: z.array(z.string()).default([]),
    cons: z.array(z.string()).default([]),
    /**
     * Retained but no longer rendered. The import made it uniform — every
     * published post is `archive` — so the label and the facet rail it drove
     * were removed from the builds pages. Kept because the field costs
     * nothing and the slot beside the section header is meant to be reused.
     */
    status: status.default('archive'),
    /** Ordinal shown as "01 —" in card metadata; also the sort key. */
    index: z.number().int().positive(),
    hero: z.string().optional(),
    gallery: z.array(z.string()).default([]),

    /* --- Imported from the Blogspot post --- */
    /**
     * Post body, one entry per paragraph, already stripped of markup. Kept as
     * plain text rather than HTML so the detail page never has to trust — or
     * sanitise — markup coming from a third-party feed.
     */
    body: z.array(z.string()).default([]),
    /** YouTube video id for the build's turntable/review clip. */
    video: z.string().optional(),
    /** Canonical Blogspot permalink, credited on the detail page. */
    sourceUrl: z.url().optional(),
    /** Post labels, kept for filtering and for the RSS categories. */
    tags: z.array(z.string()).default([]),
  }),
});

/**
 * B / GAMING LOG — platform, year, progress, rating, status, review excerpt,
 * screenshots treated as the visual anchor.
 */
const games = defineCollection({
  loader: file('./src/content/games/games.json'),
  schema: z.object({
    title: z.string(),
    platform: z.string(),
    year: z.number().int(),
    /** Percent complete, 0-100. */
    progress: z.number().min(0).max(100),
    /** Out of 10, matching "Rating 8.5 / 10". */
    rating: z.number().min(0).max(10).nullish(),
    playStatus: z.enum(['in-progress', 'finished', 'abandoned', 'backlog']),
    /** True for the single "CURRENTLY PLAYING" feature slot. */
    current: z.boolean().default(false),
    review: z.string(),
    screenshots: z.array(z.string()).default([]),
    status: status.default('archive'),
  }),
});

/**
 * C / READING LOG — title/author, source and rating, a short personal
 * thought rather than a review score, and a position on the year's timeline.
 */
const books = defineCollection({
  loader: file('./src/content/books/books.json'),
  schema: z.object({
    title: z.string(),
    author: z.string(),
    source: z.string().default('GOODREADS'),
    /** Out of 5, matching "RATING 4 / 5". */
    rating: z.number().min(0).max(5).nullish(),
    thought: z.string(),
    /** ISO date; drives the reading timeline and ordering. */
    finishedOn: z.string().optional(),
    /** True for the single "CURRENT BOOK" feature slot. */
    current: z.boolean().default(false),
    cover: z.string().optional(),
    status: status.default('archive'),
  }),
});

/**
 * D / WORKSHOP / PROJECTS — the case-study pattern:
 * problem → approach → result → stack → lessons learned.
 */
const projects = defineCollection({
  loader: file('./src/content/projects/projects.json'),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    year: z.number().int(),
    /** Curated display order, ascending. Ties on year are not meaningful. */
    order: z.number().int().positive(),
    problem: z.string(),
    approach: z.string(),
    result: z.string(),
    stack: z.array(z.string()).default([]),
    lessons: z.array(z.string()).default([]),
    status: status.default('live'),
    href: z.url().optional(),
  }),
});

export const collections = { builds, games, books, projects };
