import { defineCollection } from 'astro:content';
import { z } from 'astro/zod';
import { file, glob } from 'astro/loaders';

/**
 * Content collections — shaped from Figma "03 — Content Systems" (11:74).
 *
 * Layout follows the structure sketched in FIGMA.md. Builds, games and books
 * are one file per entry: each is generated from an external source and grows
 * without limit, and per-entry files keep a sync's diff readable. Projects
 * stay a single JSON array — hand-written and short.
 *
 * These schemas are also the contract the .NET API will need to satisfy
 * later, so they are deliberately explicit rather than loose.
 */

/** Figma "Status Label" (33:41) variants. */
const status = z.enum(['live', 'archive', 'draft']);

/**
 * A / BUILD ARCHIVE — "RG / 1:144 / MOBILE SUIT", model name,
 * "Series · Manufacturer · Build date", build notes, photo set.
 *
 * These files are generated by `npm run blog:sync` from the Blogspot feed and
 * committed. Do not hand-edit them — the next sync overwrites the file. To
 * correct or supply a field, add it to src/content/builds-overrides.json.
 *
 * `grade`, `scale` and `series` are optional because the feed cannot always
 * supply them: third-party makers (Daban, Shenma, Hemoxian) do not use Bandai
 * grade names, and non-scale kits have no meaningful scale. Every consumer
 * has to tolerate their absence rather than render an empty separator.
 */
const builds = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/builds' }),
  schema: z.object({
    title: z.string(),
    /** Kit grade — RG, MG, HG, PG. Rendered in the kicker when known. */
    grade: z.string().optional(),
    scale: z.string().optional(),
    kind: z.string(),
    series: z.string().optional(),
    manufacturer: z.string(),
    buildDate: z.string(),
    /** Empty for the occasional photo-only post that has no prose at all. */
    summary: z.string().default(''),
    /** Panel lining / custom paint / decals / modifications. */
    notes: z.array(z.string()).default([]),
    /** Bullets the post filed under "Pros:" / "Cons:", kept apart so the
     *  detail page does not present a complaint as a recommendation. */
    pros: z.array(z.string()).default([]),
    cons: z.array(z.string()).default([]),
    /**
     * Retained but no longer rendered. The import made it uniform — every
     * published post is `archive` — so the label and the facet rail it drove
     * were removed from the builds pages. Kept because the field costs
     * nothing and the slot beside the section header is meant to be reused.
     */
    status: status.default('archive'),
    /** Ordinal shown as "01 —" in card metadata; also the sort key. */
    index: z.number().int().positive(),
    hero: z.string().optional(),
    gallery: z.array(z.string()).default([]),

    /* --- Imported from the Blogspot post --- */
    /**
     * Post body, one entry per paragraph, already stripped of markup. Kept as
     * plain text rather than HTML so the detail page never has to trust — or
     * sanitise — markup coming from a third-party feed.
     */
    body: z.array(z.string()).default([]),
    /** YouTube video id for the build's turntable/review clip. */
    video: z.string().optional(),
    /** Canonical Blogspot permalink, credited on the detail page. */
    sourceUrl: z.url().optional(),
    /** Post labels, kept for filtering and for the RSS categories. */
    tags: z.array(z.string()).default([]),
  }),
});

/**
 * B / GAMING LOG — platform, year, progress, rating, status, review excerpt,
 * screenshots treated as the visual anchor.
 *
 * Generated by `npm run games:sync` from the PlayStation Network trophy and
 * played-games endpoints, and committed. Do not hand-edit these files — the
 * next sync overwrites them. Corrections, and everything PSN cannot know,
 * go in src/content/games-overrides.json.
 *
 * `rating`, `review` and `screenshots` are always empty on import: they are
 * opinion and personal capture, which no API supplies. They come from the
 * overrides file, which is where the editorial half of this section lives.
 */
const games = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/games' }),
  schema: z.object({
    title: z.string(),
    platform: z.string(),
    year: z.number().int(),
    /** Percent complete, 0-100. PSN's trophy progress for the title. */
    progress: z.number().min(0).max(100),
    /** Out of 10, matching "Rating 8.5 / 10". Override-only. */
    rating: z.number().min(0).max(10).nullish(),
    /**
     * Mostly inferred, because PSN has no notion of how you feel about a game:
     * 100% or a platinum is `finished`, a trophy within 60 days is
     * `in-progress`, and everything else is simply `played`.
     *
     * `played` is deliberately flat. The inference used to call that last
     * group `abandoned`, which labelled 190 games — most of a decade-old
     * library — as failures on no evidence. `abandoned` and `backlog` remain
     * in the enum, but only an override can claim them: giving up on
     * something is a judgement a person makes, not a sync.
     */
    playStatus: z.enum(['in-progress', 'finished', 'played', 'backlog', 'abandoned']),
    /** True for the single "CURRENTLY PLAYING" feature slot. */
    current: z.boolean().default(false),
    /** Override-only: PSN has no opinion to import. */
    review: z.string().default(''),
    /** Override-only: personal captures, not Sony's promotional art. */
    screenshots: z.array(z.string()).default([]),
    status: status.default('archive'),

    /* --- Imported from PSN --- */
    /** Earned and defined counts by grade, as PSN reports them. */
    trophies: z
      .object({
        earned: z.record(z.string(), z.number()).optional(),
        defined: z.record(z.string(), z.number()).optional(),
      })
      .default({}),
    platinum: z.boolean().default(false),
    /** Hours, to one decimal. Null where the trophy list could not be matched
     *  to a played-games record — the two endpoints use different ids. */
    playtimeHours: z.number().nullish(),
    firstPlayedOn: z.string().optional(),
    lastPlayedOn: z.string().optional(),
    /** Trophy-set icon. Square. */
    icon: z.string().optional(),
    /** Store artwork from the played-games record, where one matched. */
    art: z.string().optional(),
  }),
});

/**
 * C / READING LOG — title/author, source and rating, a short personal
 * thought rather than a review score, and a position on the year's timeline.
 *
 * Generated by `npm run books:sync` from the Goodreads per-shelf RSS feed and
 * committed. Do not hand-edit these files — the next sync overwrites them.
 * Corrections go in src/content/books-overrides.json.
 *
 * One file per book rather than a single array: the shelf runs to a few
 * hundred entries and grows, and per-book files keep a sync's diff readable.
 */
const books = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/books' }),
  schema: z.object({
    title: z.string(),
    author: z.string(),
    source: z.string().default('GOODREADS'),
    /** Out of 5, matching "RATING 4 / 5". Null where the book is unrated —
     *  Goodreads reports that as 0, which is not a rating of zero. */
    rating: z.number().min(0).max(5).nullish(),
    /**
     * Lead paragraph of the review, shown on the card and above the fold.
     * Empty for a book rated but not written about, which is roughly half
     * of them, so nothing may assume it is present.
     */
    thought: z.string().default(''),
    /** The rest of the review, one entry per paragraph. */
    review: z.array(z.string()).default([]),
    /** ISO date; drives the reading timeline and ordering. */
    finishedOn: z.string().optional(),
    /** ISO date the book was shelved — the fallback sort key for the
     *  sizeable share of entries with no finish date. */
    addedOn: z.string().optional(),
    /** True for anything on the "currently reading" shelf. */
    current: z.boolean().default(false),
    cover: z.string().optional(),
    status: status.default('archive'),

    /* --- Imported from Goodreads --- */
    pages: z.number().int().positive().nullish(),
    /** Year of the edition Goodreads has, not necessarily first publication. */
    published: z.number().int().nullish(),
    /** The community score, kept to contrast with the personal rating. */
    averageRating: z.number().min(0).max(5).nullish(),
    isbn: z.string().optional(),
    goodreadsUrl: z.url().optional(),
    /** Custom shelves the book sits on, minus the one it was fetched from. */
    shelves: z.array(z.string()).default([]),
  }),
});

/**
 * E / JOURNEYS — Flickr albums, shown as a filmstrip per album on the index
 * and a full gallery on the album's own page.
 *
 * Generated by `npm run albums:sync` from the Flickr API and committed. Do not
 * hand-edit these files — the next sync overwrites them. Corrections go in
 * src/content/albums-overrides.json.
 *
 * Photos are stored inline rather than as a second collection: an album is
 * only ever read whole, and a few hundred rows of JSON is cheaper than a
 * relation between two collections that nothing else needs.
 */
const albums = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/albums' }),
  schema: z.object({
    title: z.string(),
    /** Flickr album description. Frequently empty. */
    description: z.string().default(''),
    /** Ordinal shown as "01 —"; counts up from the oldest album so it is stable. */
    index: z.number().int().positive(),
    flickrId: z.string(),
    flickrUrl: z.url(),
    photoCount: z.number().int().nonnegative(),
    cover: z.url(),
    /** Range the photos were taken over, from EXIF where Flickr has it. */
    takenFrom: z.string().optional(),
    takenTo: z.string().optional(),
    createdOn: z.string().optional(),
    /**
     * Every photo, with both sizes and their real dimensions so the page can
     * reserve each frame's aspect ratio and not reflow as images load.
     */
    photos: z
      .array(
        z.object({
          id: z.string(),
          title: z.string().default(''),
          caption: z.string().default(''),
          thumb: z.url(),
          thumbWidth: z.number().int().positive().nullish(),
          thumbHeight: z.number().int().positive().nullish(),
          large: z.url(),
          largeWidth: z.number().int().positive().nullish(),
          largeHeight: z.number().int().positive().nullish(),
          takenOn: z.string().nullish(),
        }),
      )
      .default([]),
  }),
});

/**
 * D / WORKSHOP / PROJECTS — the case-study pattern:
 * problem → approach → result → stack → lessons learned.
 */
const projects = defineCollection({
  loader: file('./src/content/projects/projects.json'),
  schema: z.object({
    title: z.string(),
    subtitle: z.string(),
    year: z.number().int(),
    /** Curated display order, ascending. Ties on year are not meaningful. */
    order: z.number().int().positive(),
    problem: z.string(),
    approach: z.string(),
    result: z.string(),
    stack: z.array(z.string()).default([]),
    lessons: z.array(z.string()).default([]),
    status: status.default('live'),
    href: z.url().optional(),
  }),
});

export const collections = { builds, games, books, projects, albums };
